<strong>Report For Day <?=$this->escape( $this->day->dayLabel() )?></strong>:<br />
<table border="1">  
    <tr>
        <th>Hour</th>
        <th>Click</th>
    </tr>  
    <?php
    foreach( $this->day->getHours() as $hour )
    {
        ?>
        <tr>
            <td><?=$this->escape( $hour->hourLabel() )?></td>
            <td><?=$this->escape( number_format( $hour->getCount('click'), 0 ) )?></td>
        </tr>
        <?php
    }
    ?>
</table>